### ISSUE TITLE
Please ca you help with this 

### ISSUE THREAD

**Issue by vig28** [Zaseth/SherwoodBot#1]
![image](https://user-images.githubusercontent.com/65466008/82128830-162b4d00-97b6-11ea-99d0-f5f39b93523b.png)
![image-1](https://user-images.githubusercontent.com/65466008/82128841-2511ff80-97b6-11ea-8811-d6ab54d4a1bd.png)
Any help would be great thanks!

**Comment by vig28** [comment]
node version:14.0.0 python version:3.8.3

**Comment by Zaseth** [comment]
Download Chromium manually [here](https://download-chromium.appspot.com/) and extract the folder into `C:\GameBot\SherwoodBot\node_modules\puppeteer\.local-chromium\win64-737027\`

Like so in my screen:
![image](https://user-images.githubusercontent.com/24899039/82129838-29461900-97c6-11ea-952f-01e6534abe53.png)

![image](https://user-images.githubusercontent.com/24899039/82129816-fd2a9800-97c5-11ea-8f4e-d181ead003b1.png)

win64-**737027** this number can be changed, the error shows the number you need as shown below.
![image](https://user-images.githubusercontent.com/24899039/82129827-17fd0c80-97c6-11ea-9a2a-ad98ad46a4a3.png)

**Comment by vig28** [comment]
Thank you for the help I appreciate it

**Comment by Zaseth** [comment]
If you need further help or information: Zaseth#3300 on Discord.
