### ISSUE TITLE
help

### ISSUE THREAD

**Issue by laiomon** [Zaseth/SherwoodBot#2]
![bot](https://user-images.githubusercontent.com/30221676/82133210-8f7b6d80-97bf-11ea-8977-52bb0051f97b.png)

**Comment by laiomon** [comment]
![Sem título](https://user-images.githubusercontent.com/30221676/82133811-8b068300-97c6-11ea-88fe-46c4fb565fc6.png)

**Comment by Zaseth** [comment]
Please install all of the modules.
