### ISSUE TITLE
I cant run. Please help me

### ISSUE THREAD

**Issue by Mikhail512** [Zaseth/SherwoodBot#4]
When I clicked start game button, this error occupied.
![img_20200518](https://user-images.githubusercontent.com/61160800/82232359-1c116180-9961-11ea-9075-22bfd6bf2d7f.png)
Thank you in advance.

**Comment by Zaseth** [comment]
I can't reproduce this issue. What Node version are you using, and what Puppeteer version?

**Comment by Mikhail512** [comment]
node version:14.0.0
puppeteer version:3.0.4
Thank you

**Comment by Zaseth** [comment]
Please download the latest SherwoodBot, re-download all the modules `npm install` and tell me if it'll work now.

**Comment by Mikhail512** [comment]
Bot loaded.
Btw bot name is Zaseth and doesnt any action.
![bot](https://user-images.githubusercontent.com/61160800/82244895-8d0e4480-9974-11ea-95ba-4965ec55725c.png)

**Comment by Zaseth** [comment]
So the fix worked? Great! Make sure you're on a member account.

**Comment by Mikhail512** [comment]
Thank you very much.
